# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congressperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField(db_index=True, verbose_name='Applicant ID')),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
            ],
        ),
    ]
